security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        from_databaseUser:
           entity:
              class: App\Entity\User
              property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            logout: 
                path:  /logout
                target:  /front/home

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: login 
                check_path: login
                success_handler: redirect.after.login
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/profile/user, roles: ROLE_USER }
         - { path: ^/profile/teacher, roles: ROLE_TEACHER }
         - { path: ^/profile/student, roles: ROLE_STUDENT }
         - { path: ^/profile/guardian, roles: ROLE_GUARDIAN }
    encoders:
        App\Entity\User: plaintext
    #role_hierarchy:
        #ROLE_USER: [ROLE_TEACHER, ROLE_STUDENT, ROLE_GUARDIAN]
